# This is the Snakemake configuration file that specifies paths and 
# and options for the pipeline. Anybody wishing to use
# the provided snakemake pipeline should first fill out this file with paths to
# their own data, as the Snakefile requires it.
# Every config option has reasonable defaults unless it is labeled as "required."
# All paths are relative to the directory that Snakemake is executed in.
# Note: this file is written in the YAML syntax (https://learnxinyminutes.com/docs/yaml/)


# Paths to a SNP-STR haplotype reference panel for 1000G
# You can download this from http://gymreklab.com/2018/03/05/snpstr_imputation.html
# If the VCFs are per-chromosome, replace the contig name in the file name with "{chr}"
# The VCF(s) must be sorted and indexed (with a .tbi file in the same directory)
# required!
ref_panel: "/projects/ps-gymreklab/resources/datasets/snpstr/1kg.snp.str.chr{chr}.vcf.gz"

# Path to a 1000G samples TSV file
# You can get this file by clicking "Download the list" here:
# https://www.internationalgenome.org/data-portal/sample
# required!
samples: /projects/ps-gymreklab/resources/datasets/snpstr/igsr_samples.tsv

# A list of loci, specifying variants to use within the simulations
# Each locus can be specified as a dict composed of two keys:
# 1. "locus" - a string with a contig name, a colon, the start position, a dash, and the
# end position
# 2. "str" - a string with a contig name, a colon, and the start position
# 3. (optionally) "snp" - same format as "str"
#   If this key is not provided, a random SNP will be chosen.
# The STR and SNP positions should be contained within the locus.
# The positions should be provided in the same coordinate system as the reference
# genome of the VCF files.
# The contig should correspond with the contig name from the {chr} wildcard in the VCF
# required!
loci:
  - locus: 1:98001984-99001984
    str: 1:98506615
    snp: 1:98501984
  - locus: 10:104457618-105457618
    str: 10:104639652
    snp: 10:104612335

# Generates phenotypes for either SNP or STR ("snp" or "str")
# If you want to run multiple modes, just provide them in a list.
# defaults to "snp"
mode: [snp, str]

# Which 1000G superpopulation should be used?
# Please provide a three letter code, corresponding to the symbol in the samples file
# This will default to EUR (aka european ancestry), if not specified
superpop: EUR

# Discard rare variants with a MAF below this number
# Defaults to 0 if not specified
min_maf: 0

# The strength of association between the chosen STR or SNP and the simulated phenotype
# Defaults to 0.1 if not specified
# You can also provide a list of floats, if you want to test several beta values
beta: [0.05, 0.1, 0.15, 0.2, 0.25, 0.3]
